jobs:
  include:
    - language: node_js
   
env:
  - TOKEN="test"
  - PROJECT_NAME="test"
  - DEVICE_IDS= >
        [{"name":"Xiaomi Redmi Note 9 Pro","udid":"75c53f4a", "runTest": true},
        {"name":"Samsung Galaxy Tab A 10.1","udid":"R52MB0MM5WJ", "runTest": true},
        {"name": "Apple XS", "udid": "00008020-000125660279002E", "runTest": true},
        {"name": "Apple 11 Pro Max", "udid": "00008030-000431860A88802E", "runTest": true}]


robotic-mobi-automation:
  script: >-
      mvn package -DskipTests=true -q &&
      wget file.robotic.mobi/get_file_by_path?path=general-files/robotic-gitlab-appium-ci.tar.gz -O robotic-gitlab-appium-ci.tar.gz &&
      unzip robotic-gitlab-appium-ci.tar.gz &&
      cd output &&
      npm install &&
      DIR=$GITHUB_WORKSPACE TOKEN=$TOKEN DEVICE_ID=$DEVICE_IDS APP_NAME=$PROJECT_NAME TEST_NAME=$GITHUB_REPOSITORY TEST_DESC=$GITHUB_ACTION node index.js