jobs:
  include:
    - language: node_js
   
env:
  - TOKEN="test"
  - PROJECT_NAME="test"
  - DEVICE_IDS= "sadf"


robotic-mobi-automation:
  script: >-
      mvn package -DskipTests=true -q &&
      wget file.robotic.mobi/get_file_by_path?path=general-files/robotic-gitlab-appium-ci.tar.gz -O robotic-gitlab-appium-ci.tar.gz &&
      unzip robotic-gitlab-appium-ci.tar.gz &&
      cd output &&
      npm install &&
      DIR=$GITHUB_WORKSPACE TOKEN=$TOKEN DEVICE_ID=$DEVICE_IDS APP_NAME=$PROJECT_NAME TEST_NAME=$GITHUB_REPOSITORY TEST_DESC=$GITHUB_ACTION node index.js
      