name: Robotic Java CI with Maven

on: push

jobs:
  run_robotic_mobi:
    name: Robotic.mobi automation
    runs-on: ubuntu-latest
    env:
      TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtb2JpbmF2ZWwiOiJib3VuIiwiaWF0IjoxNjQxMjk2OTIyLCJleHAiOjE2NDEzMzI5MjJ9.7PsAfY66ZQQjPptkD5HKb3U_Na8wfIR8XAryTb5RXQc'
      PROJECT_NAME: 'mobile test'
      DEVICE_IDS: >
        [{"name":"Xiaomi Redmi Note 9 Pro","udid":"75c53f4a", "runTest": true},
        {"name":"Samsung Galaxy Tab A 10.1","udid":"R52MB0MM5WJ", "runTest": true}]

    steps:
      - uses: actions/checkout@v2
      - name: 'Robotic.mobi Run'
        run: |
          mvn package -DskipTests=true -q
          wget file.robotic.mobi/get_file_by_path?path=general-files/robotic-github-ci-appium-mobile-testng.tar.gz -O robotic-github-ci-appium-mobile-testng.tar.gz
          unzip robotic-github-ci-appium-mobile-testng.tar.gz
          cd output
          npm install
          DIR=$GITHUB_WORKSPACE TOKEN=$TOKEN DEVICE_ID=$DEVICE_IDS APP_NAME=$PROJECT_NAME TEST_NAME=$GITHUB_REPOSITORY TEST_DESC=$GITHUB_ACTION node index.js
